/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CycleEntry = IDL.Record({
  'endDate' : IDL.Int,
  'cycleLength' : IDL.Nat,
  'startDate' : IDL.Int,
});
export const FertilityPhase = IDL.Variant({
  'follicular' : IDL.Null,
  'ovulation' : IDL.Null,
  'menstrual' : IDL.Null,
  'luteal' : IDL.Null,
});
export const FertilityPhaseResult = IDL.Record({
  'phase' : FertilityPhase,
  'dayInCycle' : IDL.Nat,
});
export const UserPreferences = IDL.Record({
  'lutealPhaseLength' : IDL.Nat,
  'reminderDaysBefore' : IDL.Int,
  'preferredCycleLength' : IDL.Nat,
});
export const SafePeriodStatus = IDL.Variant({
  'safe' : IDL.Null,
  'unsafe' : IDL.Null,
  'caution' : IDL.Null,
});
export const SexualActivityEntry = IDL.Record({
  'date' : IDL.Int,
  'protected' : IDL.Bool,
  'notes' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCycleEntry' : IDL.Func([IDL.Int, IDL.Int], [], []),
  'addSexualActivityEntry' : IDL.Func(
      [IDL.Int, IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCycleEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteSexualActivityEntry' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentCycleDay' : IDL.Func([], [IDL.Nat], ['query']),
  'getCycleEntries' : IDL.Func([], [IDL.Vec(CycleEntry)], ['query']),
  'getFertilityPhases' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FertilityPhaseResult)],
      ['query'],
    ),
  'getPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
  'getSafePeriodStatus' : IDL.Func([IDL.Int], [SafePeriodStatus], ['query']),
  'getSexualActivityEntries' : IDL.Func(
      [],
      [IDL.Vec(SexualActivityEntry)],
      ['query'],
    ),
  'getSexualActivityEntry' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SexualActivityEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCycleEntry' : IDL.Func([IDL.Nat, IDL.Int, IDL.Int], [], []),
  'updatePreferences' : IDL.Func([UserPreferences], [], []),
  'updateSexualActivityEntry' : IDL.Func(
      [IDL.Nat, IDL.Int, IDL.Bool, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CycleEntry = IDL.Record({
    'endDate' : IDL.Int,
    'cycleLength' : IDL.Nat,
    'startDate' : IDL.Int,
  });
  const FertilityPhase = IDL.Variant({
    'follicular' : IDL.Null,
    'ovulation' : IDL.Null,
    'menstrual' : IDL.Null,
    'luteal' : IDL.Null,
  });
  const FertilityPhaseResult = IDL.Record({
    'phase' : FertilityPhase,
    'dayInCycle' : IDL.Nat,
  });
  const UserPreferences = IDL.Record({
    'lutealPhaseLength' : IDL.Nat,
    'reminderDaysBefore' : IDL.Int,
    'preferredCycleLength' : IDL.Nat,
  });
  const SafePeriodStatus = IDL.Variant({
    'safe' : IDL.Null,
    'unsafe' : IDL.Null,
    'caution' : IDL.Null,
  });
  const SexualActivityEntry = IDL.Record({
    'date' : IDL.Int,
    'protected' : IDL.Bool,
    'notes' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCycleEntry' : IDL.Func([IDL.Int, IDL.Int], [], []),
    'addSexualActivityEntry' : IDL.Func(
        [IDL.Int, IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCycleEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteSexualActivityEntry' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentCycleDay' : IDL.Func([], [IDL.Nat], ['query']),
    'getCycleEntries' : IDL.Func([], [IDL.Vec(CycleEntry)], ['query']),
    'getFertilityPhases' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FertilityPhaseResult)],
        ['query'],
      ),
    'getPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
    'getSafePeriodStatus' : IDL.Func([IDL.Int], [SafePeriodStatus], ['query']),
    'getSexualActivityEntries' : IDL.Func(
        [],
        [IDL.Vec(SexualActivityEntry)],
        ['query'],
      ),
    'getSexualActivityEntry' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SexualActivityEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCycleEntry' : IDL.Func([IDL.Nat, IDL.Int, IDL.Int], [], []),
    'updatePreferences' : IDL.Func([UserPreferences], [], []),
    'updateSexualActivityEntry' : IDL.Func(
        [IDL.Nat, IDL.Int, IDL.Bool, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };