/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CycleEntry {
  'endDate' : bigint,
  'cycleLength' : bigint,
  'startDate' : bigint,
}
export type FertilityPhase = { 'follicular' : null } |
  { 'ovulation' : null } |
  { 'menstrual' : null } |
  { 'luteal' : null };
export interface FertilityPhaseResult {
  'phase' : FertilityPhase,
  'dayInCycle' : bigint,
}
export type SafePeriodStatus = { 'safe' : null } |
  { 'unsafe' : null } |
  { 'caution' : null };
export interface SexualActivityEntry {
  'date' : bigint,
  'protected' : boolean,
  'notes' : [] | [string],
}
export interface UserPreferences {
  'lutealPhaseLength' : bigint,
  'reminderDaysBefore' : bigint,
  'preferredCycleLength' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCycleEntry' : ActorMethod<[bigint, bigint], undefined>,
  'addSexualActivityEntry' : ActorMethod<
    [bigint, boolean, [] | [string]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCycleEntry' : ActorMethod<[bigint], undefined>,
  'deleteSexualActivityEntry' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentCycleDay' : ActorMethod<[], bigint>,
  'getCycleEntries' : ActorMethod<[], Array<CycleEntry>>,
  'getFertilityPhases' : ActorMethod<[bigint], Array<FertilityPhaseResult>>,
  'getPreferences' : ActorMethod<[], [] | [UserPreferences]>,
  'getSafePeriodStatus' : ActorMethod<[bigint], SafePeriodStatus>,
  'getSexualActivityEntries' : ActorMethod<[], Array<SexualActivityEntry>>,
  'getSexualActivityEntry' : ActorMethod<[bigint], [] | [SexualActivityEntry]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCycleEntry' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'updatePreferences' : ActorMethod<[UserPreferences], undefined>,
  'updateSexualActivityEntry' : ActorMethod<
    [bigint, bigint, boolean, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];